# peers.conf — IPs de los demás nodos
#
# Formato: IP:PUERTO
# Sin puerto usa el default (8080)
# Este archivo NO incluye la IP propia del nodo.
#
# Nodo 1 (192.168.1.10) → este archivo tiene .11 y .12
# Nodo 2 (192.168.1.11) → este archivo tiene .10 y .12
# Nodo 3 (192.168.1.12) → este archivo tiene .10 y .11

192.168.1.11:8080
192.168.1.12:8080
